export {default as Bio} from './components/Bio'
export {default as Board} from './components/Board'
export {default as Avatar} from './components/Avatar'
export {default as Currently} from './components/Currently'
export {default as Projects} from './components/Projects'
export {default as Global} from './components/Global'
